version: '3'
services:
    web:
      build: .
      volumes:
        - .:/challenge
      ports:
        - 5000:80
      depends_on:
        - db
      # env_file:
        # - .env
    db:
      image: postgres:12.0-alpine
      volumes:
        - challenge-db:/var/lib/postgresql/data
volumes:
  challenge-db:
